#include <iostream>
#include <cstdlib>
using namespace std;

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char** argv) {

    int choice, random, user_num;
    
    cout<<"    **********  Welcome  to the Number Guessing Game:  **********   "<<endl<<endl;

    while (true) {
    	
    	
        cout << "  Enter your choice for the number guessing game:" << endl;
        cout << "  '1' for Beginner level where you have 20 guesses from range '1' to '25'" << endl;
        cout << "  '2' for Intermediate level where you have 15 guesses from range '1' to '50'" << endl;
        cout << "  '3' for Hard level where you have 10 guesses from range '1' to '100'" << endl;

        cin >> choice;

        if (choice > 0 && choice < 4) {
            cout << "You entered a valid choice: " << choice << endl;

            if (choice == 1) {
                random = 1 + (rand() % 25);
                int remaining_attempts = 20;

                while (remaining_attempts > 0) {
                    cout << "Guess the Number Generated by the System (1 to 25): ";
                    cin >> user_num;

                    if (user_num == random) {
                        cout << "Congrats! You guessed the right number. Entered number is " << user_num << " and the System Generated number is " << random << endl;
                        break;
                    } else if (user_num > random) {
                        cout << "Entered number is greater than the system generated number. Try again." << endl;
                    } else {
                        cout << "Entered number is lower than the system generated number. Try again." << endl;
                    }

                    remaining_attempts--;
                }

                if (remaining_attempts == 0) {
                    cout << "Sorry, you've run out of guesses. The correct number was: " << random << endl;
                }
            }
            
            else if (choice == 2) {
                random = 1 + (rand() % 50);
                int remaining_attempts = 15;

                while (remaining_attempts > 0) {
                    cout << "Guess the Number Generated by the System (1 to 50): ";
                    cin >> user_num;

                    if (user_num == random) {
                        cout << "Congrats! You guessed the right number. Entered number is " << user_num << " and the System Generated number is " << random << endl;
                        break;
                    } else if (user_num > random) {
                        cout << "Entered number is greater than the system generated number. Try again." << endl;
                    } else {
                        cout << "Entered number is lower than the system generated number. Try again." << endl;
                    }

                    remaining_attempts--;
                }

                if (remaining_attempts == 0) {
                    cout << "Sorry, you've run out of guesses. The correct number was: " << random << endl;
                }
            }
        
        else if (choice == 3) {
                random = 1 + (rand() % 100);
                int remaining_attempts = 10;

                while (remaining_attempts > 0) {
                    cout << "Guess the Number Generated by the System (1 to 100): ";
                    cin >> user_num;

                    if (user_num == random) {
                        cout << "Congrats! You guessed the right number. Entered number is " << user_num << " and the System Generated number is " << random << endl;
                        break;
                    } else if (user_num > random) {
                        cout << "Entered number is greater than the system generated number. Try again." << endl;
                    } else {
                        cout << "Entered number is lower than the system generated number. Try again." << endl;
                    }

                    remaining_attempts--;
                }

                if (remaining_attempts == 0) {
                    cout << "Sorry, you've run out of guesses. The correct number was: " << random << endl;
                }
            }
        }
       else {
            cout << "Invalid choice. Please enter a valid choice (1, 2, or 3)." << endl;
        }
    }

	return 0;
}